name: myapp

services:
  myapp:
    build: .
    environment:
      DATABASE_DSN: ${DATABASE_DSN}
    networks:
      default:
      web:
    labels:
      traefik.enable: "true"
      traefik.http.routers.myapp.rule: Host(`myapp.dbut.dev`)
      traefik.http.services.myapp.loadbalancer.server.port: "8080"
      com.centurylinklabs.watchtower.scope: myapp

networks:
  web:
    external: true
