// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	GetPageViews(ctx context.Context) (int32, error)
	IncrementPageViews(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
