name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  quality:
    uses: dbut2/x/.github/workflows/quality-go.yaml@main
  docker:
    uses: dbut2/x/.github/workflows/quality-docker.yaml@main
